export const loginPath = "/login"
export const registerPath = "/register"
export const recipesPath = "/recipes"
export const userProfile = "/profile"
export const homePath = "/"
export const usersPath="/users"
export const logoutPath = "/logout"